### ISSUE TITLE
Steer.java

### ISSUE THREAD

**Issue by marcelinalinaa** [marcelinalinaa/CarSimulator#1]
public class Steer{
    
    String direction;
    int x;
    int y;
    boolean isMoving = true;

    public Steer(){
        direction = "east";
    }

    public void setDirection(String direction){
        this.direction = direction;
    }
    public String getDirection(){
        return direction;
    } 
    public void move(String direction, Car car, Speedometer speedometer){
        x = car.getX();
        y = car.getY();
        if(isHeadingWest(direction)){
            while(isMoving){
                x = x + (int)(speedometer.speed/10);
                //update(), jadi setiap 
            }       
        }
        if(isHeadingEast(direction)){
            while(isMoving){
                x = x +(int)(speedometer.speed/10);;
            }
        }
        if(isHeadingNorth(direction)){
            while(isMoving){
                y = y + (int)(speedometer.speed/10);;
            }
        }
        if(isHeadingSouth(direction)){
            while(isMoving){
                y = y - (int)(speedometer.speed/10);;
            }
        }
    }

    public boolean isHeadingWest(String direction){
        if(direction == "west")
            return true;
        else 
            return false;
    }
    public boolean isHeadingEast(String direction){
        if(direction == "east")
            return true;
        else
            return false;
    }

    public boolean isHeadingSouth(String direction){
        if(direction == "south")
            return true;
        else
            return false;
    }
    public boolean isHeadingNorth(String direction){
        if(direction == "north")
            return true;
        else
            return false;
    }

**Comment by TEricJ** [comment]
`public class Steer{
    private char direction;

    public Steer(){
        setDirection('e');
    }

    public void setDirection(char d){
        direction = d;
    }

    public char getDirection(){
        return direction;
    }

    public void move(char d, Car car, Speedometer s){
        int x = car.getX();
        int y = car.getY();
        
        while(s.getSpeed() != 0){
            if(d == 'w'){
                x = x - (int)(s.getSpeed()/10);
            } else if(d == 'e'){
                x = x + (int)(s.getSpeed()/10);
            } else if(d == 'n'){
                y = y - `(int)(s.getSpeed()/10);`
            } else if(d == 's'){
                y = y + (int)(s.getSpeed()/10);
            }
        }
    }
}`

**Comment by marcelinalinaa** [comment]
package project;
public class Steer{
    private char direction;
    
    public Steer(){
        setDirection('e');
    }
    
    public void setDirection(char d){
        direction = d;
    }
    
    public char getDirection(){
        return direction;
    }
    
    public void move(char d, Car car, Speedometer s){
        int x = car.getX();
        int y = car.getY();
        
        while(s.getSpeed() != 0){
            if(d == 'w'){
                x = x - (s.getSpeed()/10);
            } else if(d == 'e'){
                x = x + (s.getSpeed()/10);
            } else if(d == 'n'){
                y = y - (s.getSpeed()/10);
            } else if(d == 's'){
                y = y + (s.getSpeed()/10);
            }
        }
    }
}
